example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_catalog

app_name = "katalog"

urlpatterns = [
    path("", show_catalog, name="show_catalog"),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_index
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = "mywatchlist"

urlpatterns = [
    path("", show_index, name=""),
    path("html/", show_mywatchlist, name="show_mywatchlist"),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path("katalog", include("katalog.urls")),
    path("mywatchlist/", include("mywatchlist.urls")),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user 
from todolist.views import logout_user
from todolist.views import create_todo
from todolist.views import delete_todo
from todolist.views import update_status
from todolist.views import show_xml
from todolist.views import show_json
from todolist.views import add

app_name = 'todolist'

urlpatterns = [
    path("", show_todolist, name="show_todolist"),
    path("login/", login_user, name="login"),
    path("register/", register, name="register"),
    path("create-task/", create_todo, name="create_todo"),
    path("logout/", logout_user, name="logout"),    
    path("delete/<int:id>", delete_todo, name="delete_todo"),
    path("update/<int:id>", update_status, name="update_status"),
    path("date/", show_todolist, name="update_status"),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('add/', add, name='add'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    deadline = models.TextField(default="16-02-2002")

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_catalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'name': 'Ferry',
        'student_id': '2106701936',
        'list_katalog': data_barang_katalog
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_index(request):
    return render(request, "index_mywatchlist.html")

def show_mywatchlist(request):
    return render(request, "mywatchlist.html", context)

context = {
    'list_film': MyWatchList.objects.all(),
    'name': 'Ferry',
    'student_id': '2106701936'
}

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login

from django.contrib.auth import logout

from django.views.decorators.csrf import csrf_exempt


import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from todolist.models import ToDoList

from django.http import HttpResponse
from django.core import serializers

from django.http import JsonResponse


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_objects = sorted(ToDoList.objects.filter(user=request.user), key=lambda x: x.is_finished)
    context = {
        "todolist": todolist_objects, 
        "username": request.user, 
        'last_login': request.COOKIES['last_login'],}
    return render(request, "todolist.html", context)

data_todolist = ToDoList.objects.all()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
            response.set_cookie(
                'last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url="/todolist/login/")
def create_todo(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        ToDoList.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    return render(request, "create_todo.html")

@login_required(login_url="/todolist/login/")
def delete_todo(request, id):
    todo = ToDoList.objects.get(user=request.user, id=id)
    todo.delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url="/todolist/login/")
def update_status(request, id):
    todo = ToDoList.objects.get(user=request.user, id=id)
    todo.is_finished = not todo.is_finished
    todo.save(update_fields=["is_finished"])
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

def show_xml(request):
    data = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add(request):
    if request.method == "POST":
        title = request.POST.get("judul")
        description = request.POST.get("deskripsi")
        deadline = request.POST.get("deadline")
        task = ToDoList.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
            deadline=deadline
        )
    return JsonResponse(
        {
                "pk": task.id,
                "fields": {
                    "title": task.title,
                    "description": task.description,
                    "is_finished": task.is_finished,
                    "date": task.date,
                    "deadline": task.deadline,
                },
            }
    )

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ name }}</p>

  <h5>Student ID: </h5>
  <p>{{ student_id }}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% for catalog in list_katalog %}
    <tr>
      <td>{{catalog.item_name}}</td>
      <td>{{catalog.item_price}}</td>
      <td>{{catalog.item_stock}}</td>
      <td>{{catalog.rating}}</td>
      <td>{{catalog.description}}</td>
      <td>{{catalog.item_url}}</td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/index_mywatchlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        html{
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bold;
            color: #5a6e7b;
        }
        #box1, #box2, #box3 {
            margin: 40px;
            padding: 50px;
            border-radius: 30px;
            background: #F0F3F9;
box-shadow:  6px 6px 12px #dadde3,
             -6px -6px 12px #ffffff;
        }
        #box1{
            margin-top: 70px;
        }
        body {
            background-color: #F0F3F9;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        a {
            color: inherit; /* blue colors for links too */
            text-decoration: inherit; /* no underline */
        }
        div:not(#parent):hover,
        div:not(#parent):focus {
            background: #F0F3F9;
            background: #F0F3F9;
            background: #F0F3F9;
            box-shadow: inset 6px 6px 15px #d3d6db,
                        inset -6px -6px 15px #ffffff;
        }
    </style>
</head>
<body>
    <div id="parent">
        <a href="/mywatchlist/html/">
        <div id="box1">
            HTML
        </div>
        </a>
        <a href="/mywatchlist/json/">
            <div id="box2">
                JSON
            </div>
        </a>
        <a href="/mywatchlist/xml/">
            <div id="box3">
                XML
            </div>
        </a>
    </div>
</body>
</html>

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ name }}</p>

  <h5>Student ID: </h5>
  <p>{{ student_id }}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for film in list_film %}
    <tr>
      <td>{{film.watched}}</td>
      <td>{{film.title}}</td>
      <td>{{film.rating}}</td>
      <td>{{film.release_date}}</td>
      <td>{{film.review}}</td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body class="d-flex flex-column justify-content-center align-items-center" style="padding: 50px 40px">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_todo.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
<title>Create Todo</title>
<link rel="stylesheet" href="{% static 'css/styles_create.css' %}">
{% endblock meta %}

{% block content %}

<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %}
<div id="boxlogin" class="d-flex flex-column align-items-center" style="gap: 16px">
    <h5>Tambah Task</h5>
    <div class="d-flex flex-row align-items-evenly flex-wrap">
        <div>
            <label for="title">Title:</label>
            <input type="text" name="title" placeholder="Judul task">
        </div>
    
        <div>
            <label for="description">Description:</label>
            <input type="text" name="description" placeholder="Deskripsi task">

        </div>
        <button type="submit" class="btn btn-primary">Create Task</button>
    </div>


</div>
</form>

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'css/styles_login.css' %}">
{% endblock meta %}

{% block content %}

<div class = "login " id="boxlogin">

    <h1>Welcome!</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    <input type="text" name="username" placeholder="Username" class="form-control">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="password" name="password" placeholder="Password" class="form-control">
                </td>
            </tr>

            <tr>
                <td>
                    <input class="btn login_btn btn-primary btn-block mb-4" type="submit" value="Login">
                </td>
            </tr>
        </table>
    </form>

    {% if messages %}
            {% for message in messages %}
                <p id="eror">{{ message }}</p>
            {% endfor %}
    {% endif %}     
        
    <p>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></p> 

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Registrasi Akun</title>
<link rel="stylesheet" href="{% static 'css/styles_register.css' %}">
    
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>
                <tr>
                    <td>
                        <button>
                            <a href="{% url 'todolist:login' %}">Batal</a>
                        </button>
                    </td>
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}